FARGO_SIG	equ	$0032
EXE_TYPE	equ	'EXE '
DLL_SUBTYPE	equ	'DLL '
APPL_SUBTYPE	equ	'APPL'
PRGM_SUBTYPE	equ	'PRGM'

TIOS_EXPORTS		equ	_tios_count
KERNEL_EXPORTS		equ	$0001

TIOS_PSEUDOHANDLE	equ	$FFFE
KERNEL_PSEUDOHANDLE	equ	$FFFF

FLAG0_PACK_TABLES	equ	0
RESERVED_FLAGS		equ	$FFFE
